In [1]:
from tiatoolbox.models.engine.general_segmentor import GeneralSegmentor
from tiatoolbox.models.architecture.sam import SAM, SAMPrompts 

# abc = GeneralSegmentor(model=SAM())
# prompts = SAMPrompts([[100,100]])
# output = abc.predict("slides/sample_wsi.svs", prompts, "cpu", "abcdefg")

|2025-02-21|20:20:16.830| [WARNING] /dcs/22/u2208490/.conda/envs/tiatoolbox-dev/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

|2025-02-21|20:20:20.003| [WARNING] /dcs/22/u2208490/.conda/envs/tiatoolbox-dev/lib/python3.11/site-packages/albumentations/__init__.py:28: UserWarning: A new version of Albumentations is available: '2.0.4' (you have '2.0.1'). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()



In [2]:
from pathlib import Path
model = GeneralSegmentor(SAM())

glands = "slides/glands.png"
slides = "slides/sample_wsi.svs"
glands_prompts = [(370,270),(300,400)]
slides_prompts = [[2200,2700]]


|2025-02-21|20:20:22.151| [INFO] Loaded checkpoint sucessfully


In [3]:
prompts = model.create_prompts(glands_prompts)
output = model.predict(glands, prompts, "cpu", "overlays")


|2025-02-21|20:20:22.336| [WARNING] Raw data is None.
|2025-02-21|20:20:22.337| [WARNING] Unknown scale (no objective_power or mpp)


|2025-02-21|20:20:22.349| [INFO] For numpy array image, we assume (HxWxC) format
|2025-02-21|20:20:22.408| [INFO] Computing image embeddings for the provided image...
|2025-02-21|20:20:23.381| [INFO] Image embeddings computed.
[[[0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  ...
  [1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]]]
Prediction stored at /dcs/22/u2208490/cs310/tiatoolbox/examples/overlays


In [4]:

save_path = model.to_annotation(output[0][1], output[0][2], Path("overlays/glands.png"))



Annotations stored at overlays/glands.db
