In [2]:
from tiatoolbox.models.engine.general_segmentor import GeneralSegmentor
from tiatoolbox.models.architecture.sam import SAM, SAMPrompts 

# abc = GeneralSegmentor(model=SAM())
# prompts = SAMPrompts([[100,100]])
# output = abc.predict("slides/sample_wsi.svs", prompts, "cpu", "abcdefg")

|2025-02-18|15:41:21.192| [WARNING] /dcs/22/u2208490/.conda/envs/tiatoolbox-dev/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

|2025-02-18|15:41:24.560| [WARNING] /dcs/22/u2208490/.conda/envs/tiatoolbox-dev/lib/python3.11/site-packages/albumentations/__init__.py:28: UserWarning: A new version of Albumentations is available: '2.0.4' (you have '2.0.1'). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()



In [20]:
import numpy as np
x = np.load(output[0][1] + ".npy")
print(x)

FileNotFoundError: [Errno 2] No such file or directory: '/dcs/22/u2208490/cs310/tiatoolbox/examples/overlays/0.npy.npy'

In [ ]:
# data = np.fromfile("abcdefg/file_map.dat", dtype=np.float32)  # Adjust dtype as needed
# print(data)
import pickle

with open("abcdefg/file_map.dat", "rb") as f:
    #paths = f.readlines()
    paths2 = pickle.load(f)

#print(paths)
print(paths2)

paths = [path.strip() for path in paths]
print(paths)


[['slides/sample_wsi.svs', '/dcs/22/u2208490/cs310/tiatoolbox/examples/abcdefg/0']]


NameError: name 'paths' is not defined

In [15]:
from pathlib import Path
model = GeneralSegmentor(SAM())

glands = "slides/glands.png"
slides = "slides/sample_wsi.svs"
glands_prompts = [[370,270]]
slides_prompts = [[2200,2700]]


|2025-02-18|15:48:55.974| [INFO] Loaded checkpoint sucessfully


In [17]:
prompts = model.create_prompts(slides_prompts)
output = model.predict(slides, prompts, "cpu", "overlays")


|2025-02-18|15:49:18.584| [INFO] For numpy array image, we assume (HxWxC) format
|2025-02-18|15:49:19.062| [INFO] Computing image embeddings for the provided image...
|2025-02-18|15:49:19.996| [INFO] Image embeddings computed.


In [ ]:

save_path = model.to_annotation(output[0][1], Path("overlays/sample_wsi.svs"))



[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
POLYGON ((1896 3201, 1895 3202, 1893 3202, 1892 3203, 1889 3203, 1888 3204, 1885 3204, 1884 3205, 1881 3205, 1880 3206, 1877 3206, 1876 3207, 1872 3207, 1871 3208, 1866 3208, 1865 3209, 1861 3209, 1860 3210, 1855 3210, 1856 3211, 1860 3211, 1861 3212, 1863 3212, 1864 3213, 1866 3213, 1867 3214, 1869 3214, 1871 3216, 1872 3216, 1879 3223, 1879 3224, 1880 3225, 1880 3226, 1881 3227, 1881 3228, 1882 3229, 1882 3231, 1883 3232, 1883 3235, 1884 3236, 1884 3241, 1885 3242, 1885 3248, 1886 3249, 1886 3259, 1887 3260, 1887 3265, 1888 3266, 1888 3270, 1889 3271, 1889 3274, 1890 3275, 1890 3277, 1891 3278, 1891 3279, 1892 3280, 1892 3281, 1893 3282, 1893 3283, 1894 3284, 1894 3285, 1898 3289, 1898 3288, 1900 3286, 1900 3285, 1903 3282, 1903 3281, 1905 3279, 1905 3278, 1909 3274, 1909 3273, 1914 3268, 1914 3267, 1924 3257, 1924 3253, 1