In [1]:
from tiatoolbox.wsicore.wsireader import WSIReader
from tiatoolbox.visualization.tileserver import TileServer
from tiatoolbox.cli.visualize import run_bokeh
#wsi = WSIReader.open("tmp/sample_wsi.svs")
# app = TileServer(
#     title="Testing TileServer",
#     layers={
#         "My SVS": wsi,
#     },
# )
#app.run()

#run_bokeh([""], 5006, noshow=True)  # pragma: no cover

|2025-01-30|18:30:56.781| [WARNING] /dcs/22/u2208490/.conda/envs/tiatoolbox-dev/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

|2025-01-30|18:31:02.589| [WARNING] /dcs/22/u2208490/.conda/envs/tiatoolbox-dev/lib/python3.11/site-packages/albumentations/__init__.py:28: UserWarning: A new version of Albumentations is available: '2.0.2' (you have '2.0.1'). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()



In [5]:
from tiatoolbox.models.engine.general_segmentor import GeneralSegmentor
from tiatoolbox.models.architecture.sam import SAM, SAMPrompts

abc = GeneralSegmentor(model=SAM())
prompts = SAMPrompts([[100,100]])
abc.predict("tmp/sample_wsi.svs", prompts, "cpu", "abcdefg")

|2025-01-30|22:18:16.373| [INFO] Loaded checkpoint sucessfully
|2025-01-30|22:18:25.429| [INFO] For numpy array image, we assume (HxWxC) format
|2025-01-30|22:18:25.477| [INFO] Computing image embeddings for the provided image...
|2025-01-30|22:18:26.392| [INFO] Image embeddings computed.


array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.]]], dtype=float32)

In [6]:
import numpy as np
x = np.load("")
print(x)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [0. 0. 0. ... 1. 1. 1.]
  [0. 0. 0. ... 1. 1. 1.]
  [0. 0. 0. ... 1. 1. 1.]]]


In [7]:
data = np.fromfile("abcdefg/file_map.dat", dtype=np.float32)  # Adjust dtype as needed
print(data)

[1.3107725e+15 0.0000000e+00 5.7646075e+17 5.6609571e-26 1.7223624e+22
 1.3900641e+31 1.1626349e+27 1.9598879e+31 1.2330756e+33 6.7033710e-05
 1.8015798e+31 1.6206834e-10 6.4827727e-10 6.7376815e-10 5.6668053e-08
 5.5519372e+31 7.5632104e+28 7.0074700e+28 1.8593731e+34 1.1626349e+27
 2.0228095e+20 6.7408303e+22 6.3811567e-10 7.8024122e+34]
